osx_image: xcode7.3
language: objective-c
env:
  matrix:
    - PLATFORM=iOS SDK=iphonesimulator SCHEME=TrueTime-iOS
    - PLATFORM=Mac SDK=macosx SCHEME=TrueTime-Mac
install: 
  - gem install xcpretty
  - carthage bootstrap --platform "$PLATFORM"
script:
  - BUILD_LOG="xcodebuild.log"
  - xcodebuild clean test -sdk "$SDK" -scheme "$SCHEME" | tee "$BUILD_LOG" | xcpretty
  - STATUS="${PIPESTATUS[0]}"
  - if [ -f "$BUILD_LOG" ]; then curl -sT "$BUILD_LOG" chunk.io; fi
  - bash -c "exit $STATUS"

cache:
  directories:
  - Carthage/Build
