osx_image: xcode7.3
language: objective-c
install: carthage bootstrap --platform ios
xcode_project: TrueTime.xcodeproj
xcode_scheme: TrueTime
cache:
  directories:
  - Carthage/Build
xcode_sdk: iphonesimulator
