osx_image: xcode7.3
language: objective-c
env:
  matrix:
    - PLATFORM=iOS SDK=iphonesimulator SCHEME=TrueTime-iOS
    - PLATFORM=Mac SDK=macosx SCHEME=TrueTime-Mac
    - PLATFORM=tvOS SDK=appletvsimulator SCHEME=TrueTime-tvOS
install: 
  - gem install xcpretty
  - carthage bootstrap --platform "$PLATFORM"
script:
  - Scripts/test
cache:
  directories:
    - Carthage/Build
