osx_image: xcode7.3
language: objective-c
install: carthage bootstrap --platform ios
xcode_project: NetworkTime.xcodeproj
xcode_scheme: NetworkTime
cache:
  directories:
  - Carthage/Build
xcode_sdk: iphonesimulator
