osx_image: xcode7.3
language: objective-c
env:
  matrix:
    - PLATFORM=iOS SDK=iphonesimulator SCHEME=TrueTime-iOS
    - PLATFORM=Mac SDK=macosx SCHEME=TrueTime-Mac
install: 
  - carthage bootstrap --platform "$PLATFORM"
script:
  - xctool clean test -sdk "$SDK" -scheme "$SCHEME"
cache:
  directories:
  - Carthage/Build
